### ISSUE TITLE
Cannot access Vexchange via App Hub (desktop app / linux)

### ISSUE THREAD

**Issue by fede-rodes** [Monti/vexchange#27]
**Bug Description**
I'm using the desktop version ./Sync-linux-x86_64-1.3.0.AppImage from https://github.com/vechain/thor-sync.electron to access all vechain apps. Prior to v2 release I was able to access the exchange but after the release I get a blank screen.

**Steps to Reproduce**
1. Install ./Sync-linux-x86_64-1.3.0.AppImage from https://github.com/vechain/thor-sync.electron
2. Launch Vexchange app
...

**Expected Behavior**
Access the vexchange app

**Additional Context**
![Screenshot from 2021-08-27 09-30-09](https://user-images.githubusercontent.com/16927407/131114282-86f986e8-144e-49bd-90fa-472b8f1fcb4f.png)

**Comment by OliverNChalk** [comment]
Interesting, @KennethAshley I assume this is due to the current issues with supporting Connex V1? I.e. Sync V1 runs on Connex V1 and that's probably causing this bug?

**Comment by KennethAshley** [comment]
@OliverNChalk Yep this is the the Connex v1 vs Connex v2 issue. 

@fede-rodes fix coming soon!
