### ISSUE TITLE
Arkane Wallet Display & Management

### ISSUE THREAD

**Issue by OliverNChalk** [Monti/vexchange#7]
Arkane stores multiple wallets per user, along with a human readable name for each wallet. As such, we need to implement:
 - Displaying the human readable wallet name if the user has an arkane wallet.
 - Link to the wallet control page as done in this example: https://demo.arkane.network/

**Comment by karelstriegel** [comment]
The best solution would be to have a dropdown on vexchange.io , so if users want to work with 2 vechain wallets they can switch easily, without having to "manage" their linked wallets. 

Example from thorblock:

![image](https://user-images.githubusercontent.com/6882032/51672631-413fcb00-1fcc-11e9-9556-f8f2a2c5c127.png)

**Comment by OliverNChalk** [comment]
Done with #8
